"""
Security pattern library – 24 curated patterns.
"""
from __future__ import annotations
from typing import Any, Dict, List

SECURITY_PATTERNS: List[Dict[str, Any]] = [
    {
        "id": "SP-001",
        "name": "Strong Authentication",
        "category": "Authentication",
        "description": "Verify user identity through robust credential mechanisms before granting access.",
        "problem": "Systems without strong authentication are vulnerable to spoofing and impersonation.",
        "stride_categories": ["Spoofing"],
        "component_types": ["service", "api", "user"],
        "implementation": (
            "Implement OAuth 2.0/OIDC, enforce password complexity, use bcrypt/Argon2 for hashing, "
            "and enforce account lockout after failed attempts."
        ),
        "benefits": "Prevents unauthorised access; establishes user identity.",
        "limitations": "Adds friction for users; requires secure credential storage.",
        "example": "OAuth 2.0 with PKCE for web applications.",
        "priority": "Critical",
    },
    {
        "id": "SP-002",
        "name": "Multi-Factor Authentication",
        "category": "Authentication",
        "description": "Require two or more independent factors to authenticate a user.",
        "problem": "Single-factor authentication can be bypassed by credential theft.",
        "stride_categories": ["Spoofing"],
        "component_types": ["service", "user", "api"],
        "implementation": "Combine password + TOTP (e.g., Google Authenticator) or hardware token.",
        "benefits": "Drastically reduces account takeover risk.",
        "limitations": "Increases user friction; requires secondary channel infrastructure.",
        "example": "TOTP-based MFA for admin portals.",
        "priority": "Critical",
    },
    {
        "id": "SP-003",
        "name": "Role-Based Access Control",
        "category": "Authorization",
        "description": "Restrict operations based on roles assigned to users or services.",
        "problem": "Without RBAC, any authenticated entity can perform privileged actions.",
        "stride_categories": ["ElevationOfPrivilege", "Tampering"],
        "component_types": ["service", "database", "api"],
        "implementation": "Define roles (admin, user, service), assign minimal permissions, enforce at API layer.",
        "benefits": "Limits blast radius of compromised accounts.",
        "limitations": "Role explosion can occur in large systems.",
        "example": "Spring Security @PreAuthorize annotations.",
        "priority": "High",
    },
    {
        "id": "SP-004",
        "name": "Attribute-Based Access Control",
        "category": "Authorization",
        "description": "Grant access based on attributes of users, resources, and environment.",
        "problem": "RBAC alone may be too coarse for fine-grained access requirements.",
        "stride_categories": ["ElevationOfPrivilege"],
        "component_types": ["service", "api"],
        "implementation": "Use policy engines (e.g., OPA, AWS IAM conditions) to evaluate dynamic attributes.",
        "benefits": "Highly flexible and context-aware access control.",
        "limitations": "Complex to design and audit.",
        "example": "Allow access only if user.department == resource.owner_department.",
        "priority": "Medium",
    },
    {
        "id": "SP-005",
        "name": "Least Privilege",
        "category": "Authorization",
        "description": "Grant entities only the permissions they need and nothing more.",
        "problem": "Excessive permissions amplify the impact of a compromise.",
        "stride_categories": ["ElevationOfPrivilege"],
        "component_types": ["service", "database", "api"],
        "implementation": "Audit and trim permissions regularly; use service accounts with scoped roles.",
        "benefits": "Minimises damage from insider threats and account compromise.",
        "limitations": "Requires ongoing maintenance as requirements change.",
        "example": "Database user with SELECT-only access for reporting services.",
        "priority": "High",
    },
    {
        "id": "SP-006",
        "name": "Encryption in Transit",
        "category": "Cryptography",
        "description": "Protect data from eavesdropping and tampering while in transit using TLS.",
        "problem": "Plaintext communication exposes data to interception and modification.",
        "stride_categories": ["InformationDisclosure", "Tampering"],
        "component_types": ["service", "api", "database", "queue"],
        "implementation": "Enforce TLS 1.2+ on all connections; use HSTS; disable weak ciphers.",
        "benefits": "Prevents eavesdropping and man-in-the-middle attacks.",
        "limitations": "Certificate management overhead; slight performance impact.",
        "example": "Nginx with TLS 1.3 and HSTS enabled.",
        "priority": "Critical",
    },
    {
        "id": "SP-007",
        "name": "Encryption at Rest",
        "category": "Cryptography",
        "description": "Protect stored data from unauthorised access using encryption.",
        "problem": "Unencrypted storage exposes data if physical or logical access is obtained.",
        "stride_categories": ["InformationDisclosure", "Tampering"],
        "component_types": ["database", "storage"],
        "implementation": "Use AES-256 for database encryption; encrypt backup files; manage keys securely.",
        "benefits": "Data is useless to attackers without the decryption key.",
        "limitations": "Performance overhead; key management complexity.",
        "example": "PostgreSQL with pgcrypto or AWS RDS encryption.",
        "priority": "High",
    },
    {
        "id": "SP-008",
        "name": "Input Validation",
        "category": "Input Handling",
        "description": "Validate all input data against expected format, length, type, and range.",
        "problem": "Unvalidated input enables injection attacks and data corruption.",
        "stride_categories": ["Tampering", "ElevationOfPrivilege"],
        "component_types": ["service", "api"],
        "implementation": "Apply whitelist validation; reject unexpected input; use schema validators.",
        "benefits": "Prevents SQL injection, XSS, and command injection.",
        "limitations": "Requires continuous updates as input schemas evolve.",
        "example": "JSON Schema validation with Pydantic.",
        "priority": "Critical",
    },
    {
        "id": "SP-009",
        "name": "Output Encoding",
        "category": "Input Handling",
        "description": "Encode output data to prevent injection in target rendering contexts.",
        "problem": "Unencoded output enables XSS and template injection.",
        "stride_categories": ["Tampering", "InformationDisclosure"],
        "component_types": ["service", "api"],
        "implementation": "Context-aware encoding (HTML, URL, JS, SQL); use templating engines with auto-escaping.",
        "benefits": "Eliminates reflected and stored XSS vulnerabilities.",
        "limitations": "Must be applied consistently to every output point.",
        "example": "Jinja2 with autoescaping=True.",
        "priority": "High",
    },
    {
        "id": "SP-010",
        "name": "Secure Session Management",
        "category": "Authentication",
        "description": "Manage user sessions securely to prevent hijacking and fixation.",
        "problem": "Weak session management allows session theft and replay attacks.",
        "stride_categories": ["Spoofing"],
        "component_types": ["service", "api"],
        "implementation": "Use cryptographically random session IDs; enforce expiry; invalidate on logout.",
        "benefits": "Prevents session fixation and hijacking.",
        "limitations": "Distributed session management adds infrastructure complexity.",
        "example": "Signed JWT with short expiry and refresh token rotation.",
        "priority": "High",
    },
    {
        "id": "SP-011",
        "name": "API Gateway",
        "category": "Infrastructure",
        "description": "Centralise API traffic management, security, and observability at a single entry point.",
        "problem": "Distributed API endpoints are harder to secure consistently.",
        "stride_categories": ["DenialOfService", "Spoofing", "ElevationOfPrivilege"],
        "component_types": ["api", "service"],
        "implementation": "Deploy API gateway (Kong, AWS API Gateway); enforce auth, rate limiting, and TLS termination.",
        "benefits": "Single point for security policy enforcement.",
        "limitations": "Single point of failure if not redundant; can become a bottleneck.",
        "example": "Kong Gateway with JWT plugin and rate-limiting plugin.",
        "priority": "High",
    },
    {
        "id": "SP-012",
        "name": "Rate Limiting",
        "category": "Availability",
        "description": "Limit request frequency to prevent abuse, brute force, and DoS.",
        "problem": "Unlimited request rates enable brute force and volumetric attacks.",
        "stride_categories": ["DenialOfService"],
        "component_types": ["api", "service"],
        "implementation": "Apply per-IP and per-user rate limits; use sliding window algorithms.",
        "benefits": "Limits brute force and DDoS impact.",
        "limitations": "Legitimate burst traffic may be throttled.",
        "example": "nginx limit_req_zone with burst=20.",
        "priority": "High",
    },
    {
        "id": "SP-013",
        "name": "Secure Logging",
        "category": "Monitoring",
        "description": "Capture security-relevant events in tamper-resistant, structured logs.",
        "problem": "Without logging, attacks go undetected and investigations fail.",
        "stride_categories": ["Repudiation"],
        "component_types": ["service", "api", "database"],
        "implementation": "Log auth events, errors, and sensitive operations; ship logs to centralised SIEM.",
        "benefits": "Enables attack detection, forensics, and compliance.",
        "limitations": "Logs may contain sensitive data; storage costs.",
        "example": "ELK Stack with structured JSON logging.",
        "priority": "High",
    },
    {
        "id": "SP-014",
        "name": "Audit Trail",
        "category": "Monitoring",
        "description": "Maintain an immutable chronological record of security-relevant events.",
        "problem": "Without audit trails, users can deny actions; compliance fails.",
        "stride_categories": ["Repudiation"],
        "component_types": ["service", "database"],
        "implementation": "Write-once audit tables; sign log entries with HMAC; retain for regulatory period.",
        "benefits": "Non-repudiation; regulatory compliance; forensic capability.",
        "limitations": "Storage costs; must protect audit data from tampering.",
        "example": "Append-only audit table with event hash chain.",
        "priority": "High",
    },
    {
        "id": "SP-015",
        "name": "Integrity Verification",
        "category": "Cryptography",
        "description": "Detect unauthorised modification of data using checksums or digital signatures.",
        "problem": "Data can be silently modified in transit or at rest.",
        "stride_categories": ["Tampering"],
        "component_types": ["service", "storage", "database"],
        "implementation": "Use HMAC or SHA-256 checksums; verify on read; sign API responses.",
        "benefits": "Detects data corruption and tampering.",
        "limitations": "Requires key management; adds latency.",
        "example": "S3 object with MD5/SHA-256 checksum validation.",
        "priority": "Medium",
    },
    {
        "id": "SP-016",
        "name": "Digital Signatures",
        "category": "Cryptography",
        "description": "Cryptographically sign data to prove origin and prevent repudiation.",
        "problem": "Without signatures, data provenance cannot be verified.",
        "stride_categories": ["Repudiation", "Tampering"],
        "component_types": ["service", "api"],
        "implementation": "Use RSA or ECDSA signatures on critical payloads and audit records.",
        "benefits": "Non-repudiation; tamper detection; origin verification.",
        "limitations": "Key management overhead; performance cost.",
        "example": "Signed JWTs or XML digital signatures.",
        "priority": "Medium",
    },
    {
        "id": "SP-017",
        "name": "Secrets Management",
        "category": "Configuration",
        "description": "Store and access credentials, API keys, and certificates securely.",
        "problem": "Hardcoded or file-stored secrets are easily exfiltrated.",
        "stride_categories": ["InformationDisclosure"],
        "component_types": ["service", "api", "database"],
        "implementation": "Use HashiCorp Vault, AWS Secrets Manager, or K8s Secrets with encryption.",
        "benefits": "Centralised rotation; prevents secret sprawl.",
        "limitations": "Additional infrastructure dependency.",
        "example": "Vault dynamic database credentials.",
        "priority": "High",
    },
    {
        "id": "SP-018",
        "name": "Network Segmentation",
        "category": "Infrastructure",
        "description": "Divide networks into zones with controlled traffic between them.",
        "problem": "Flat networks allow lateral movement after initial compromise.",
        "stride_categories": ["InformationDisclosure", "ElevationOfPrivilege"],
        "component_types": ["service", "database", "api"],
        "implementation": "Use VPCs, subnets, firewalls, and security groups to isolate zones.",
        "benefits": "Limits blast radius; prevents lateral movement.",
        "limitations": "Complex to manage; can hinder legitimate inter-service communication.",
        "example": "AWS VPC with public/private subnet separation.",
        "priority": "High",
    },
    {
        "id": "SP-019",
        "name": "Circuit Breaker",
        "category": "Availability",
        "description": "Automatically stop requests to failing services to prevent cascading failures.",
        "problem": "Slow or failing dependencies can exhaust resources and bring down entire systems.",
        "stride_categories": ["DenialOfService"],
        "component_types": ["service", "api"],
        "implementation": "Implement circuit breaker pattern (Hystrix, Resilience4j); define thresholds and fallbacks.",
        "benefits": "Improves system resilience; prevents cascade failures.",
        "limitations": "Requires careful threshold tuning.",
        "example": "Resilience4j circuit breaker with fallback response.",
        "priority": "Medium",
    },
    {
        "id": "SP-020",
        "name": "Redundancy and Failover",
        "category": "Availability",
        "description": "Deploy multiple instances with automatic failover to maintain availability.",
        "problem": "Single instances create availability risks under load or failure.",
        "stride_categories": ["DenialOfService"],
        "component_types": ["service", "database", "api"],
        "implementation": "Active-active or active-passive clusters; health checks; load balancers.",
        "benefits": "High availability; eliminates single points of failure.",
        "limitations": "Higher infrastructure cost; data synchronisation complexity.",
        "example": "PostgreSQL with streaming replication and PgBouncer.",
        "priority": "High",
    },
    {
        "id": "SP-021",
        "name": "Security Headers",
        "category": "Web Security",
        "description": "Use HTTP security headers to protect against common web attacks.",
        "problem": "Missing headers expose web apps to XSS, clickjacking, and MIME sniffing.",
        "stride_categories": ["Tampering", "InformationDisclosure"],
        "component_types": ["service", "api"],
        "implementation": "Set HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy.",
        "benefits": "Mitigates browser-level attacks with minimal effort.",
        "limitations": "CSP configuration can break legitimate functionality.",
        "example": "Django SecurityMiddleware with SECURE_HSTS_SECONDS.",
        "priority": "Medium",
    },
    {
        "id": "SP-022",
        "name": "Zero Trust",
        "category": "Architecture",
        "description": "Never trust, always verify – treat every request as potentially hostile.",
        "problem": "Perimeter-based security fails once an attacker is inside the network.",
        "stride_categories": ["Spoofing", "ElevationOfPrivilege", "InformationDisclosure"],
        "component_types": ["service", "api", "database"],
        "implementation": "Verify identity for every request; use micro-segmentation; apply least privilege.",
        "benefits": "Eliminates implicit trust; reduces insider threat risk.",
        "limitations": "Requires significant architecture and culture change.",
        "example": "Google BeyondCorp model.",
        "priority": "High",
    },
    {
        "id": "SP-023",
        "name": "Token-Based Authentication",
        "category": "Authentication",
        "description": "Use cryptographically signed tokens to authenticate stateless service-to-service calls.",
        "problem": "Session-based auth doesn't scale in distributed microservices.",
        "stride_categories": ["Spoofing"],
        "component_types": ["service", "api"],
        "implementation": "Issue short-lived JWTs; validate signature, expiry, and claims on every request.",
        "benefits": "Stateless; scales horizontally; supports cross-domain auth.",
        "limitations": "Token revocation is complex before expiry.",
        "example": "JWT Bearer tokens with RS256 signing.",
        "priority": "High",
    },
    {
        "id": "SP-024",
        "name": "Database Access Control",
        "category": "Data Security",
        "description": "Restrict database access to authorised services with minimal permissions.",
        "problem": "Unrestricted database access enables data theft and injection.",
        "stride_categories": ["Tampering", "InformationDisclosure", "ElevationOfPrivilege"],
        "component_types": ["database", "service"],
        "implementation": "Separate DB users per service; use stored procedures; enforce column-level security.",
        "benefits": "Limits data access scope; prevents cross-service data leakage.",
        "limitations": "Complex to manage in large microservice environments.",
        "example": "Row-level security in PostgreSQL.",
        "priority": "High",
    },
]

# Build a lookup dict for fast access
PATTERN_BY_NAME: Dict[str, Dict] = {p["name"]: p for p in SECURITY_PATTERNS}
PATTERN_BY_ID:   Dict[str, Dict] = {p["id"]:   p for p in SECURITY_PATTERNS}


def get_all_patterns() -> List[Dict]:
    return SECURITY_PATTERNS


def get_pattern_by_name(name: str) -> Dict:
    return PATTERN_BY_NAME.get(name, {})


def get_patterns_for_stride(category: str) -> List[Dict]:
    return [p for p in SECURITY_PATTERNS if category in p.get("stride_categories", [])]
